excluded:
 - Tests/Asn1DerTests/XCTestManifests.swift
 - Tests/Asn1DerTests/TestVectors/

switch_case_alignment:
    indented_cases: true

disabled_rules:
 - force_cast
 - file_length
 - vertical_whitespace
 - trailing_whitespace
 - force_try
