#if !canImport(ObjectiveC)
import XCTest

extension VirtualFileProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VirtualFileProviderTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VirtualFileProviderTests.__allTests__VirtualFileProviderTests),
    ]
}
#endif
